---
# Directory linting rules for the dirlint project
# All allowed files and directories must be explicitly listed

# Documentation
- README.md
- EXAMPLES.md

# Package configuration
- package.json
- package-lock.json
- tsconfig.json
- nodemon.json

# Source files
- index.ts  # Main CLI entry point
- generate_examples_file.ts
- test.ts

# Scripts and config
- publish.sh
- .gitignore
- .prettierrc

# Required directories
- /src  # Source TypeScript files
- /bin  # Compiled JavaScript output

# Optional directories
- /test_directories  # Test fixtures
- /.git
- /.github
- /.claude
- /node_modules
