---
# Rules for the analyse_directory module
# All TypeScript files must be explicitly listed
- index.ts
- analyse_directory.ts
- analyse_and_report.ts
- get_files_in_directory.ts
- get_directories_in_directory.ts
- get_items_in_directory.ts
